apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-etcd-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pki
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: etcd CA
  secretName: {{ include "headless-kubernetes.fullname" . }}-etcd-ca
  duration: 87600h
  renewBefore: 2160h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - cert sign
  issuerRef:
    name: {{ include "headless-kubernetes.fullname" . }}-selfsigned
    kind: Issuer
    group: cert-manager.io
