apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-kubernetes-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pki
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.pki.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ca:
    secretName: {{ include "headless-kubernetes.fullname" . }}-kubernetes-ca
