apiVersion: v1
kind: Service
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-etcd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: etcd
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "1"
spec:
  ports:
    - name: client
      targetPort: client
      port: 2379
    - name: peer
      targetPort: peer
      port: 2380
  selector:
    app.kubernetes.io/component: etcd
    {{- include "headless-kubernetes.selectorLabels" . | nindent 4 }}
  type: ClusterIP
