apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-nodes-files
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nodes
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "3"
data:
{{ (.Files.Glob "ansible/files/*").AsConfig | indent 2 }}
