{{ if .Values.nodes.join }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-join-nodes
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nodes
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nodes
        {{- include "headless-kubernetes.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ansible-playbook
          image: {{ .Values.nodes.image.repository }}:{{ .Values.nodes.image.tag }}
          imagePullPolicy: {{ .Values.nodes.image.pullPolicy }}
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "false"
            - name: ANSIBLE_ROLES_PATH
              value: "/tmp"
          workingDir: "/etc/ansible"
          command:
            - sh
            - -c
            - |
                ansible-galaxy install -r requirements.yaml
                ansible-playbook -i inventory.yaml playbook.yaml
          volumeMounts:
            - name: ansible
              mountPath: /etc/ansible
            - name: ssh
              mountPath: /etc/ansible/ssh
            - name: kube-proxy
              mountPath: /etc/ansible/certs/kube-proxy
            {{- range .Values.nodes.nodes }}
            - name: kubelet-{{ .name }}
              mountPath: /etc/ansible/certs/kubelet-{{ .name }}
            {{- end }}
      restartPolicy: Never
      volumes:
        - name: ansible
          configMap:
            name: {{ include "headless-kubernetes.fullname" . }}-nodes
        - name: ansible-files
          configMap:
            name: {{ include "headless-kubernetes.fullname" . }}-nodes-files
        - name: ansible-templates
          configMap:
            name: {{ include "headless-kubernetes.fullname" . }}-nodes-templates
        - name: ssh
          secret:
            secretName: {{ .Values.nodes.sshSecretName }}
            defaultMode: 0400
        - name: kube-proxy
          secret:
            secretName: {{ include "headless-kubernetes.fullname" . }}-kube-proxy
        {{- range .Values.nodes.nodes }}
        - name: kubelet-{{ .name }}
          secret:
            secretName: {{ include "headless-kubernetes.fullname" $ }}-kubelet-{{ .name }}
        {{- end }}
{{ end }}
