kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: /etc/kubelet/ca.crt
authorization:
  mode: Webhook
clusterDomain: cluster.local
clusterDNS:
  - {{ kube_cluster_dns }}
resolvConf: /run/systemd/resolve/resolv.conf
runtimeRequestTimeout: 15m
tlsCertFile: /etc/kubelet/tls.crt
tlsPrivateKeyFile: /etc/kubelet/tls.key
