apiVersion: v1
kind: Config
current-context: default
contexts:
  - name: default
    context:
      cluster: default
      user: default
clusters:
  - cluster:
      certificate-authority: ./ca.crt
      server: {{ kube_api_endpoint }}
    name: default
users:
  - name: default
    user:
      client-certificate: ./tls.crt
      client-key: ./tls.key
