apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-controllers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controllers
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
data:
  config.yaml: |
    apiVersion: v1
    kind: Config
    current-context: default
    contexts:
      - name: default
        context:
          cluster: default
          user: default
    clusters:
      - cluster:
          certificate-authority: ./client-auth/ca.crt
          server: https://{{ include "headless-kubernetes.fullname" . }}-apiserver:443
        name: default
    users:
      - name: default
        user:
          client-certificate: ./client-auth/tls.crt
          client-key: ./client-auth/tls.key
