apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller-manager
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
spec:
  commonName: system:kube-controller-manager
  secretName: {{ include "headless-kubernetes.fullname" . }}-controller-manager 
  duration: 8760h0m0s
  renewBefore: 120h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
  issuerRef:
    name: {{ include "headless-kubernetes.fullname" . }}-kubernetes-ca
    kind: Issuer
    group: cert-manager.io
