{{ if .Values.kubectl.adminCli.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-kubectl
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kubectl
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
spec:
  replicas: {{ .Values.kubectl.adminCli.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: kubectl
      {{- include "headless-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubectl
        {{- include "headless-kubernetes.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: kubectl
          image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag | default .Values.cluster.version }}
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/config.yaml
          command:
            - bash
            - -c
            - sleep infinity
          volumeMounts:
            - name: client-auth
              mountPath: /etc/kubernetes/client-auth
            - name: config
              mountPath: /etc/kubernetes/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: client-auth
          secret:
            secretName: {{ include "headless-kubernetes.fullname" . }}-kubectl
        - name: config
          configMap:
            name: {{ include "headless-kubernetes.fullname" . }}-kubectl
{{ end }}
