{{ if .Values.kubectl.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-kubectl
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kubectl
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.kubectl.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: kubectl
      {{- include "headless-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubectl
        {{- include "headless-kubernetes.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - image: bitnami/kubectl:1.24.4
          name: kubectl
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/config.yaml
          command:
            - bash
            - -c
            - sleep infinity
          volumeMounts:
            - name: config
              mountPath: /etc/kubernetes/config.yaml
              subPath: config.yaml
            - name: client-auth
              mountPath: /etc/kubernetes/client-auth
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ include "headless-kubernetes.fullname" . }}-kubectl
        - name: client-auth
          secret:
            secretName: {{ include "headless-kubernetes.fullname" . }}-kubectl
{{ end }}
