{{ if .Values.kubectl.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-kubectl
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kubectl
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.kubectl.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  commonName: admin
  secretName: {{ include "headless-kubernetes.fullname" . }}-kubectl 
  subject:
    organizations:
      - system:masters
  duration: 8760h0m0s
  renewBefore: 120h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
  issuerRef:
    name: {{ include "headless-kubernetes.fullname" . }}-kubernetes-ca
    kind: Issuer
    group: cert-manager.io
{{ end }}
