apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-post-install
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: post-install
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "3"
data:
  kubelet-api-admin-clusterrolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: system:kubelet-api-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:kubelet-api-admin
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: kubernetes
  cluster-info-configmap.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cluster-info
      namespace: kube-public
    data:
      kubeconfig: |
        apiVersion: v1
        clusters:
          - cluster:
              certificate-authority-data: SERVER_CA_B64
              server: https://{{ .Values.cluster.clusterLbAddress }}:{{ .Values.apiserver.nodePort }}
            name: ""
        contexts: []
        current-context: ""
        kind: Config
        preferences: {}
        users: []
