apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-post-install
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: post-install
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
data:
  kubelet-api-admin-clusterrolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: system:kubelet-api-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:kubelet-api-admin
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: kubernetes
