apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-encryption-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
stringData:
  config.yaml: |
    apiVersion: v1
    kind: EncryptionConfig
    resources:
      - resources:
          - secrets
        providers:
          - aescbc:
              keys:
                - name: key1
                  secret: {{ .Values.apiserver.encryptionKey }}
          - identity: {}
