apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-apiserver-kubelet-client-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
spec:
  commonName: kubernetes
  secretName: {{ include "headless-kubernetes.fullname" . }}-apiserver-kubelet-client-auth
  duration: 8760h0m0s
  renewBefore: 120h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - system:masters
  usages:
    - client auth
  issuerRef:
    name: {{ include "headless-kubernetes.fullname" . }}-kubernetes-ca
    kind: Issuer
    group: cert-manager.io
