apiVersion: v1
kind: Service
metadata:
  name: {{ include "headless-kubernetes.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "headless-kubernetes.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "2"
spec:
  type: NodePort
  ports:
    - name: https
      targetPort: https
      port: 443
      nodePort: {{ .Values.apiserver.nodePort }}
  selector:
      app.kubernetes.io/component: apiserver
      {{- include "headless-kubernetes.selectorLabels" . | nindent 6 }}
